import { person, newsletter, social, home, about, blog, work, gallery } from './content';
import { createI18nContent } from './content-i18n';
import { i18n } from './config';

/**
 * @name renderContent
 * @description
 * Conditionally renders content based on whether internationalization (i18n) is enabled.
 * If `i18n` is true, it returns the localized content generated by `createI18nContent`.
 * Otherwise, it returns the default, non-localized content.
 * @param {function} [t] - The translation function from `next-intl`. Required if i18n is enabled.
 * @returns {object} An object containing all the content for the site.
 */
const renderContent = (t) => {
    if ( i18n ) {
        return createI18nContent(t);
    } else {
        return {
            person,
            social,
            newsletter,
            home,
            about,
            blog,
            work,
            gallery
        }
    }
};

export { renderContent };